# Generated by Django 5.1.3 on 2024-11-24 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('trade_type', models.CharField(max_length=10)),
                ('entry_datetime', models.DateTimeField(blank=True, null=True)),
                ('exit_datetime', models.DateTimeField(blank=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('exit_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('quantity', models.IntegerField(default=1)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('note', models.TextField(blank=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='trades.strategy')),
                ('trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='trades.trade')),
            ],
        ),
    ]
