# Generated by Django 5.1.3 on 2024-12-31 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_coachrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='screenshot',
        ),
    ]
